version: '3.9'
services:
  mydis:
    image: dolfly/mydis
    environment:
      - TZ=Asia/Shanghai
      - MYDIS_ADDRESS=:6380
      - MYDIS_DRIVER=mysql
      - MYDIS_DEBUG=true
    ports:
      - '6380:6380'
    depends_on:
      - master01
      - master02
    configs:
      - source: my_mydis-conf
        target: /apps/conf/mydis.yaml
    networks:
      - mynet
  master01:
    image: mysql:5.7
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_USER: kvstore
      MYSQL_PASSWORD: kvstore
      MYSQL_DATABASE: kvstore
    configs:
      - source: my_init01
        target: /docker-entrypoint-initdb.d/init.sql
      - source: my_master01-conf
        target: /etc/mysql/conf.d/docker.cnf
    networks:
      - mynet
  master02:
    image: mysql:5.7
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_USER: kvstore
      MYSQL_PASSWORD: kvstore
      MYSQL_DATABASE: kvstore
    configs:
      - source: my_init02
        target: /docker-entrypoint-initdb.d/init.sql
      - source: my_master02-conf
        target: /etc/mysql/conf.d/docker.cnf
    networks:
      - mynet
configs:
  my_master01-conf:
    name: my_master01-conf-${MYVER:-0}
    file: ./conf/master01.cnf
  my_master02-conf:
    name: my_master02-conf-${MYVER:-0}
    file: ./conf/master02.cnf
  my_init01:
    name: my_init01-${MYVER:-0}
    file: ./scripts/sql/init01.sql
  my_init02:
    name: my_init02-${MYVER:-0}
    file: ./scripts/sql/init02.sql
  my_mydis-conf:
    name: my_mydis-conf-${MYVER:-0}
    file: ./conf/mydis.yaml
networks:
  mynet:
    driver: overlay